Repository Real-Dev-Squad/website-dashboard, pull requests merged in 2023-05, with the labels that each got.

#347 User inDiscord Feature - UI
  __tests__/users/App.test.js
  __tests__/users/user-management-home-screen.test.js
  constants.js
  mock-data/users/index.js
  user-management/App.js
  user-management/components/NoUserFound.js
  user-management/components/TabsSection.js
  user-management/components/UserDetailsSection.js
  user-management/components/UsersSection.js
  user-management/data.js
  user-management/index.html
  user-management/index.js
  user-management/style.css
  user-management/utils/react.js
  user-management/utils/util.js
Labels: feature task

#366 show error message for archived users
  discord-groups/script.js
Labels: bug, beginner friendly

#364 bug: update package puppeteer
  package.json
  yarn.lock
Labels: dependencies
